# File generated by Setupinit


__all__ = []


# TODO: implement commands for loading/dumping bin file from/into files
# example: paradict dump src.dict dest.bin
# example: paraidct load src.bin dest.dict

def main():
    print("https://github.com/pyrustic/paradict")


if __name__ == "__main__":
    main()
